---
- name: Install eastbayforeveryone.org
  hosts: all

  roles:
    - role: common
    - role: eastbayforeveryone.org
      tarsnap_enabled: false
      user: eb4e
      directory: "/home/{{ user }}"
      wordpress_version: '6.3.1'
      akismet_version: '5.1'
      pdf_embedder_version: '4.6.4'
      events_calendar_version: '6.2.0.1'
      progress_bar_version: '2.2.3'
      wordpress_ssl_enabled: true
      wordpress_debug: false
      domain: eastbayforeveryone.org
      redirect_domains:
        - www.eastbayforeveryone.org

# certbot certonly --non-interactive --webroot -w /home/eb4e/public -d eastbayforeveryone.org --renew-by-default --email kevin@burke.dev --text --agree-tos
# certbot certonly --non-interactive --webroot -w /home/eb4e/public -d www2.eastbayforeveryone.org --renew-by-default --email kevin@burke.dev --text --agree-tos
# certbot certonly --non-interactive --webroot -w /home/eb4e/public -d www.eastbayforeveryone.org --renew-by-default --email kevin@burke.dev --text --agree-tos
