- group: name={{ user }} state=present

- ansible.builtin.user:
    name: "{{ user }}"
    group: "{{ user }}"
    groups: "{{ user }}"
    append: yes

- ansible.builtin.user:
    name: php
    groups: "{{ user }}"
    append: yes

- name: Create remote tmp
  ansible.builtin.file:
    path: "/home/{{ user }}/.ansible/tmp"
    state: directory
    mode: 0755
    owner: "{{ user }}"
    group: "{{ user }}"

- file: path={{ directory }}/.ssh
        state=directory
        mode=0755
        group={{ user }}
  become: yes
  become_user: "{{ user }}"

- file: path={{ directory }}/public
        state=directory
        mode=0755
        group={{ user }}
  become: yes
  become_user: "{{ user }}"

- name: create letsencrypt cert verification directory
  file: path={{ directory }}/public/.well-known
        state=directory
        mode=0755
        group={{ user }}
  become: yes
  become_user: "{{ user }}"

- name: Create temp directory
  ansible.builtin.file: path={{ directory }}/tmp
        state=directory
        mode=0755
        group={{ user }}
  become: yes
  become_user: "{{ user }}"

- name: Get the akismet repo
  get_url: url={{ akismet_url }}
           dest={{ directory }}/tmp/akismet-{{ akismet_version }}.zip
  become: yes
  become_user: "{{ user }}"

- name: copy tarball to remote folder
  ansible.builtin.copy:
    src: ./tarballs/divi.zip
    dest: "{{ directory }}/tmp/divi.zip"
    owner: "{{ user }}"
    group: "{{ user }}"

- name: unzip the Divi theme
  ansible.builtin.unarchive:
    src: "{{ directory }}/tmp/divi.zip"
    dest: "{{ directory }}/wordpress/wp-content/themes"
    remote_src: yes
