---
- group: name=letsencrypt state=present

- name: Create the letsencrypt user
  ansible.builtin.user:
    name: letsencrypt
    groups:
      - letsencrypt
    append: yes

- name: Create remote tmp
  ansible.builtin.file:
    path: /home/letsencrypt/.ansible/tmp
    state: directory
    mode: 0755
    owner: letsencrypt
    group: letsencrypt

- ansible.builtin.apt:
    name: [
      'rsync',
    ]
    state: latest

# you can't install up to date certbot with apt
- name: Install core/snapd
  community.general.snap:
    name:
      - core

- name: Update snap core
  command: snap refresh core

# you can't install up to date certbot with apt
- name: Install certbot
  community.general.snap:
    name: certbot
    classic: yes

- name: symlink certbot command into place
  ansible.builtin.file:
    src: /snap/bin/certbot
    dest: /usr/bin/certbot
    state: link

# keeping local permissions in sync got very difficult so we just store them
# with kevin:staff and then chown root:root in the next task.
- name: copy letsencrypt certs to remote server
  synchronize: src=certs/
               dest=/etc/letsencrypt/
               mode=push
               links=yes
               owner=yes
               set_remote_user=no
  become: yes
  become_user: root

- name: set root:root on all files
  file: path=/etc/letsencrypt
        recurse=yes
        owner=root
        group=root
        follow=yes

- name: set up cron
  ansible.builtin.include_tasks:
    file: cron.yml
