---
- group: name=nginx

- user: name=nginx groups=nginx append=yes

- name: Create remote tmp
  ansible.builtin.file:
    path: /home/nginx/.ansible/tmp
    state: directory
    mode: 0755
    owner: nginx
    group: nginx

- ansible.builtin.file:
    path: "{{ nginx_conf | dirname }}"
    state: directory
    mode: 0755
    owner: nginx
    group: nginx

- ansible.builtin.apt:
    name: nginx
    state: latest

- file: path={{ nginx_include_dir }} state=directory mode=0755
  become: yes
  become_user: nginx
  notify: reload nginx

- name: copy logrotate script
  copy: src=logrotate
        dest=/etc/logrotate.d/nginx
        mode=644

- template: src=nginx.initd
            dest=/etc/init.d/nginx
            owner=nginx
            group=nginx
            mode=0755
  notify: reload nginx

- ansible.builtin.template:
    src: nginx.conf
    dest: "{{ nginx_conf }}"
    owner: nginx
    group: nginx
  notify: reload nginx

- name: generate Diffie Hellman parameters
  command: "openssl dhparam -out {{ diffiehellman }} 2048"
  args:
    creates: "{{ diffiehellman }}"
  become: yes
  become_user: nginx
  notify: reload nginx

- name: ensure nginx starts when the server restarts
  file: state=link
        src={{ nginx_initd }}
        dest=/etc/rc3.d/S03nginx
  notify: reload nginx

- file: path={{ nginx_log_dir }} group=nginx owner=nginx state=directory mode=0755
  notify: reload nginx
